//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Action_Back {
            get {
                return ResourceManager.GetString("Action_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Action_Confirm {
            get {
                return ResourceManager.GetString("Action_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me.
        /// </summary>
        public static string Action_ContactMe {
            get {
                return ResourceManager.GetString("Action_ContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my account.
        /// </summary>
        public static string Action_DeleteAccount {
            get {
                return ResourceManager.GetString("Action_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Now.
        /// </summary>
        public static string Action_LoginNow {
            get {
                return ResourceManager.GetString("Action_LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Action_LogOut {
            get {
                return ResourceManager.GetString("Action_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string Action_RegisterNow {
            get {
                return ResourceManager.GetString("Action_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Action_Send {
            get {
                return ResourceManager.GetString("Action_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        public static string Action_UpdatePassword {
            get {
                return ResourceManager.GetString("Action_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Action_UpdateUser {
            get {
                return ResourceManager.GetString("Action_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Common_About {
            get {
                return ResourceManager.GetString("Common_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Common_Account {
            get {
                return ResourceManager.GetString("Common_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Common_Avatar {
            get {
                return ResourceManager.GetString("Common_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat rooms.
        /// </summary>
        public static string Common_ChatRooms {
            get {
                return ResourceManager.GetString("Common_ChatRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Common_Contact {
            get {
                return ResourceManager.GetString("Common_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Common_Home {
            get {
                return ResourceManager.GetString("Common_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Common_Language {
            get {
                return ResourceManager.GetString("Common_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Common_Privacy {
            get {
                return ResourceManager.GetString("Common_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Common_Terms {
            get {
                return ResourceManager.GetString("Common_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Common_Users {
            get {
                return ResourceManager.GetString("Common_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Content_AlreadyAnAccount {
            get {
                return ResourceManager.GetString("Content_AlreadyAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete your account, you need to provide your password. Be carefull, all your information will be deleted..
        /// </summary>
        public static string Content_DeleteAccountConfirmation {
            get {
                return ResourceManager.GetString("Content_DeleteAccountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with everyone.
        /// </summary>
        public static string Content_HomeSubTitle {
            get {
                return ResourceManager.GetString("Content_HomeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing stuff!.
        /// </summary>
        public static string Content_HomeTitle {
            get {
                return ResourceManager.GetString("Content_HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string Content_NoAccountYet {
            get {
                return ResourceManager.GetString("Content_NoAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todo: privacy body.
        /// </summary>
        public static string Content_PrivacyBody {
            get {
                return ResourceManager.GetString("Content_PrivacyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todo: terms body.
        /// </summary>
        public static string Content_TermsBody {
            get {
                return ResourceManager.GetString("Content_TermsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {2} and {1} characters long..
        /// </summary>
        public static string Error_BadLength {
            get {
                return ResourceManager.GetString("Error_BadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user name or password..
        /// </summary>
        public static string Error_CannotLogin {
            get {
                return ResourceManager.GetString("Error_CannotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or email already registered..
        /// </summary>
        public static string Error_CannotRegistered {
            get {
                return ResourceManager.GetString("Error_CannotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        public static string Error_IsRequired {
            get {
                return ResourceManager.GetString("Error_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be a valid email address..
        /// </summary>
        public static string Error_NotValid {
            get {
                return ResourceManager.GetString("Error_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Error_PasswordMatching {
            get {
                return ResourceManager.GetString("Error_PasswordMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Field_Email {
            get {
                return ResourceManager.GetString("Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Field_Message {
            get {
                return ResourceManager.GetString("Field_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Field_Password {
            get {
                return ResourceManager.GetString("Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual password.
        /// </summary>
        public static string Field_PasswordActual {
            get {
                return ResourceManager.GetString("Field_PasswordActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password.
        /// </summary>
        public static string Field_PasswordConfirmation {
            get {
                return ResourceManager.GetString("Field_PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Field_PasswordNew {
            get {
                return ResourceManager.GetString("Field_PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Field_Title {
            get {
                return ResourceManager.GetString("Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Field_UserName {
            get {
                return ResourceManager.GetString("Field_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message.
        /// </summary>
        public static string PlaceHolder_Message {
            get {
                return ResourceManager.GetString("PlaceHolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sended..
        /// </summary>
        public static string Succes_EmailSended {
            get {
                return ResourceManager.GetString("Succes_EmailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated.
        /// </summary>
        public static string Success_PasswordUpdated {
            get {
                return ResourceManager.GetString("Success_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated.
        /// </summary>
        public static string Success_UserUpdated {
            get {
                return ResourceManager.GetString("Success_UserUpdated", resourceCulture);
            }
        }
    }
}
